from Router import Router, packet
import sys
import random
from matrix_utils import *
import time

class Network:
    def __init__(self: "Network", initialRouters: int, averageLinksPerNode: int = 4, connectionRadius: int = 3):
        """
        Initializes a network with a specified number of routers.

        The network is generated by creating routers and attempting to establish
        connections between them. Each router will have an approximate number of
        links based on `averageLinksPerNode`. The actual number of links may vary
        by approximately ±1 (can be more or less, but usually within this range).

        Args:
            initialRouters: The initial number of routers to create in the  network.
            averageLinksPerNode (int, optional): The approximate average number of
                connections each router should have.
            connectionRadius: The maximum ID distance between two
                routers for them to be considered as potential connection
                candidates. Routers with IDs within this range have a chance of
                being connected.
                connectionRadius = -1 means that any router can connect with any
                other router
        """

        print(f"New network created with {initialRouters} routers, {averageLinksPerNode} average links, and a connection radius of {connectionRadius == -1 and "inf" or connectionRadius}")

        self.routers: list[Router] = []
        self.routerById: dict[int, Router] = {}
        self.averageLinksPerNode = averageLinksPerNode
        self.connectionRadius = connectionRadius

        # creating routers
        for _ in range(initialRouters):
            newRouter = Router()
            self.routers.append(newRouter)
            self.routerById[newRouter.id] = newRouter

        #> linking routers
        # linking each router linearly first (to gurantee connectedness)
        for i in range(1, initialRouters):
            cost = random.randint(1, 10)
            self.routers[i].add_neighbor(self.routers[i-1], cost)
            self.routers[i-1].add_neighbor(self.routers[i], cost)

        # linking routers randomly, but only with routers within connectionRadius
        for routerPosition, routerA in enumerate(self.routers):
            searchMin = connectionRadius == -1 and 0 or max(routerPosition - connectionRadius, 0)
            searchMax = connectionRadius == -1 and (len(self.routers) - 1) or min(routerPosition + connectionRadius, len(self.routers) - 1)
            for _ in range(averageLinksPerNode):
                routerB = self.routers[random.randint(searchMin, searchMax)]
                if routerA != routerB:
                    cost = random.randint(1, 10)
                    routerA.add_neighbor(routerB, cost)
                    routerB.add_neighbor(routerA, cost)
        #< linking routers
    
    def print_network_topology(self: "Network"):
        print("Network matrix:")
        print_adjacency_matrix(self.routers, create_adjacency_matrix(self.routers))
        print()

    def add_router(self: "Network"):
        newRouter = Router()
        self.routerById[newRouter.id] = newRouter
        randRouterPosition = random.randint(0, len(self.routers) - 1)
        self.routers.insert(randRouterPosition, newRouter)
        searchMin = self.connectionRadius == -1 and 0 or max(randRouterPosition - self.connectionRadius, 0)
        searchMax = self.connectionRadius == -1 and (len(self.routers) - 1) or min(randRouterPosition + self.connectionRadius, len(self.routers) - 1)
        
        print(f"New router created: {newRouter}")
        
        for _ in range(self.averageLinksPerNode):
            otherRouter = self.routers[random.randint(searchMin, searchMax)]
            if newRouter != otherRouter:
                cost = random.randint(1, 10)
                newRouter.add_neighbor(otherRouter, cost)
                otherRouter.add_neighbor(newRouter, cost)
                print(f"Neighboring link {newRouter} <-> {otherRouter}")
        print() 
        
    def send_packet(self: "Network", fromRouterId: int, toRouterId: int, payload: str = "sample_payload") -> packet:
        if fromRouterId not in self.routerById or toRouterId not in self.routerById:
            print("One or both the routers do not exist!\n")
            return

        fromRouter = self.routerById[fromRouterId]
        toRouter = self.routerById[toRouterId]
        newPacket = fromRouter.create_packet(toRouter, payload)

        print("Attempt to send packet")
        fromRouter.send_packet(newPacket)
        print()

        return newPacket

    def send_random_packet(self: "Network") -> packet:
        # sends a random packet from a router to another router
        return self.send_packet(
            self.routers[random.randint(0, len(self.routers) - 1)].id,
            self.routers[random.randint(0, len(self.routers) - 1)].id,
            "random_packet"
        )

    def disconnect_random_router(self: "Network"):
        # simulates a random router disconnecting from the network
        chosenRounter = self.routers[random.randint(0, len(self.routers) - 1)]

        print(f"Disconneted router: {chosenRounter}")
        for neighbor in chosenRounter.get_neighbors():
            print(f"Link removed: {chosenRounter} <-> {neighbor}")
        print()

        self.routers.remove(chosenRounter)
        del self.routerById[chosenRounter.id]
        chosenRounter.disconnect()
        
    def disconnect_random_link(self: "Network"):
        # simulates a link being disconnected between two routers
        selectedRouter = self.routers[random.randint(0, len(self.routers) - 1)]
        routerNeighbors = selectedRouter.get_neighbors()
        if len(routerNeighbors) > 0:
            selectedNeighbor = routerNeighbors[random.randint(0, len(routerNeighbors) - 1)]
            selectedRouter.remove_neighbor(selectedNeighbor)
            selectedNeighbor.remove_neighbor(selectedRouter)

            print(f"Disconneted link: {selectedRouter} <-> {selectedNeighbor}\n")
        else:
            print(f"Randomly selected router has no link to disconnect\n")

if __name__ == "__main__":
    args = sys.argv[1:]

    initialRouters = 0
    averageLinksPerNode = None
    connectionRadius = None

    try:
        initialRouters = len(args) > 0 and int(args[0]) or 2
        averageLinksPerNode = len(args) > 1 and int(args[1]) or 4
        connectionRadius = len(args) > 2 and int(args[2]) or 3
    except:
        print("Invalid Arguments")
    
    newNetwork = Network(initialRouters, averageLinksPerNode, connectionRadius)

    print("\nAt this point, routers haven't built their hop tables yet. Let's try sending packets:\n")
    newNetwork.send_random_packet()
    newNetwork.send_random_packet()

    print("Waiting for network to build routing table")
    time.sleep(0.1) # waiting for network to build jump tables
    newNetwork.print_network_topology()

    newNetwork.send_random_packet()
    newNetwork.send_random_packet()

    newNetwork.add_router()
    print("Waiting for network to build routing table")
    time.sleep(0.1) # waiting for network to build jump tables
    newNetwork.print_network_topology()

    newNetwork.send_random_packet()
    newNetwork.send_random_packet()

    newNetwork.disconnect_random_router()
    print("Waiting for network to build routing table")
    time.sleep(0.1) # waiting for network to build jump tables

    newNetwork.send_random_packet()
    newNetwork.send_random_packet()

    newNetwork.print_network_topology()
    newNetwork.disconnect_random_link()
    newNetwork.disconnect_random_link()
    newNetwork.disconnect_random_link()
    print("Waiting for network to build routing table")
    time.sleep(0.1) # waiting for network to build jump tables

    newNetwork.print_network_topology()
    newNetwork.send_random_packet()
    newNetwork.send_random_packet()

    print(f"Here's an example of the internal routing table of router {newNetwork.routers[0]}")
    print(newNetwork.routers[0].next_hop)